services:
  db:
    image: postgres:16
    container_name: cloudDbApp
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_NAME: ${DB_NAME}
    ports:
      - "5432:5432"


